version: '3'

services:
  user-service:
    build:
      context: ./user_service
    ports:
      - "8001:8000"
    depends_on:
      - db

  property-service:
    build:
      context: ./property_service
    ports:
      - "8002:8000"
    depends_on:
      - db

  booking-service:
    build:
      context: ./booking_service
    ports:
      - "8003:8000"
    depends_on:
      - db

  payment-service:
    build:
      context: ./payment_service
    ports:
      - "8004:8000"
    depends_on:
      - db


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
